# Generated by Django 5.1.5 on 2025-02-14 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('data_analise', models.DateTimeField(auto_now_add=True, verbose_name='data da análise')),
                ('contemViolencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data da notificação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do repositório')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('privado', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='rep_imgs/', verbose_name='imagem do repositório')),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='colaboradores', to=settings.AUTH_USER_MODEL)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Repositorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sem título', max_length=70)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='videos/', verbose_name='arquivo de video')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='data de upload')),
                ('analise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.analisevideo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('repositorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.repositorio')),
            ],
        ),
    ]
