# Generated by Django 5.1.5 on 2025-02-04 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data da análise')),
                ('contemViolencia', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16, unique=True, verbose_name='nome de usuário')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de upload'),
        ),
        migrations.AddField(
            model_name='video',
            name='descricao',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=70),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/', verbose_name='arquivo de video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='video',
            name='analise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.analisevideo'),
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do repositório')),
                ('descricao', models.CharField(max_length=255)),
                ('privado', models.BooleanField()),
                ('imagem', models.ImageField(null=True, upload_to='imagens/', verbose_name='imagem do repositório')),
                ('colaboradores', models.ManyToManyField(blank=True, related_name='colaboradores', to='app.usuario')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data da notificação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
