# Generated by Django 5.1.5 on 2025-02-23 18:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_repositorio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to=app.models.upload_to, verbose_name='arquivo de video'),
        ),
    ]
