# Generated by Django 5.1.5 on 2025-02-04 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_analisevideo_usuario_remove_video_filename_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='criador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='imagem do repositório'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de upload'),
        ),
        migrations.AlterField(
            model_name='video',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
