# Generated by Django 5.1.5 on 2025-02-21 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_video_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='analise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.analisevideo'),
        ),
    ]
