# Generated by Django 5.1.5 on 2025-02-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_repositorio_criador_alter_video_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorio',
            name='colaboradores',
        ),
    ]
