# Generated by Django 5.1.5 on 2025-03-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
        ('app', '0005_alter_video_analise'),
    ]

    operations = [
    ]
