# Generated by Django 5.1.5 on 2025-02-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_repositorio_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='repositorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.repositorio'),
        ),
    ]
