# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUsernamejexiste():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_usernamejexiste(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.LINK_TEXT, "Click here to sign up.").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("alunofocus")
    self.driver.find_element(By.CSS_SELECTOR, ".cadastro_button__x0lFs").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".cadastro_button__x0lFs")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
