# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCancelamentodesenha():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cancelamentodesenha(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "email").send_keys("alunofocus")
    self.driver.find_element(By.ID, "password").send_keys("1234567890")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678900")
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login_container__KYhhc").click()
    self.driver.find_element(By.ID, "password").send_keys("1234567890")
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(3) > .menu_icon__xA9Da").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(1) > input").send_keys("1234567890")
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(2) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(2) > input").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(3) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_userInput__4MX2J:nth-child(3) > input").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_secondLine__PLnHP").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".undefined:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".menu_btn__qOXrA:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(1) > .menu_icon__xA9Da").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu_btn__qOXrA:nth-child(4) > .menu_showText__5wClD").click()
    self.driver.find_element(By.ID, "email").send_keys("alunofocus")
    self.driver.find_element(By.ID, "password").send_keys("1234567890")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login_container__KYhhc").click()
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
  
