# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestReproduodevideo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_reproduodevideo(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.ID, "email").send_keys("alunofocus")
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home_repositoryFlex__64oE-:nth-child(2) p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".repository_videoThumbnail__UJHP1 > img").click()
  
