# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCriarrepositorio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_criarrepositorio(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("novoaluno")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".undefined:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".home_searchbar__7Fo6G").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home_buttonCriarRepositorio__C\\+eDn > svg").click()
    self.driver.find_element(By.ID, "repositoryName").click()
    self.driver.find_element(By.ID, "repositoryName").send_keys("Novo Repositorio 1249")
    self.driver.find_element(By.ID, "repositoryDescription").send_keys("Descricao ")
    self.driver.find_element(By.ID, "repositoryName").click()
    self.driver.find_element(By.ID, "repositoryDescription").click()
    self.driver.find_element(By.ID, "repositoryDescription").send_keys("Descricao 1249")
    self.driver.find_element(By.CSS_SELECTOR, ".createRepository_buttonCreateRepository__JTnzn").click()
    assert self.driver.switch_to.alert.text == "Repositório cadastrado com sucesso!"
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".repository_searchbar__t2JOh").click()
  
