# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditarrepositorio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editarrepositorio(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(945, 1012)
    self.driver.find_element(By.ID, "email").send_keys("alunofocus")
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".login_button__0KgLi").click()
    self.driver.find_element(By.CSS_SELECTOR, ".home_repositoryFlex__64oE-:nth-child(4) p").click()
    self.driver.find_element(By.CSS_SELECTOR, "svg:nth-child(7) > circle").click()
    self.driver.find_element(By.ID, "repositoryName").click()
    self.driver.find_element(By.ID, "repositoryName").send_keys("Editar Repositório")
    self.driver.find_element(By.ID, "repositoryDescription").click()
    self.driver.find_element(By.ID, "repositoryDescription").send_keys("Meu Repositório foi editado")
    self.driver.find_element(By.CSS_SELECTOR, ".updateRepository_buttonUpdateRepository__3YwYy").click()
    assert self.driver.switch_to.alert.text == "Repositório editado com sucesso!"
  
