# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdicionarvdeosaorepositrio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adicionarvdeosaorepositrio(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".home_repositoryFlex__64oE-:nth-child(2) p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".repository_uploadButton__zAK7b > svg").click()
    self.driver.find_element(By.ID, "videoUpload").send_keys("C:\\fakepath\\26531-357855224_tiny.mp4")
    assert self.driver.switch_to.alert.text == "Vídeos enviados com sucesso!"
    self.driver.find_element(By.CSS_SELECTOR, ".repository_videoThumbnail__UJHP1").click()
    self.driver.find_element(By.CSS_SELECTOR, "video").click()
    self.driver.find_element(By.CSS_SELECTOR, "circle").click()
  
