# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCadastrobemsucedido():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cadastrobemsucedido(self):
    self.driver.get("http://localhost:3000/login")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.LINK_TEXT, "Click here to sign up.").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("novoaluno")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("novoaluno@email.com")
    self.driver.find_element(By.CSS_SELECTOR, ".cadastro_inputGroup__DgtDI:nth-child(3)").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("123456789")
    self.driver.find_element(By.ID, "confirmPassword").click()
    self.driver.find_element(By.ID, "confirmPassword").send_keys("123456789")
    self.driver.find_element(By.CSS_SELECTOR, ".cadastro_button__x0lFs").click()
    assert self.driver.switch_to.alert.text == "Usuário cadastrado com sucesso! Redirecionando para Login"
  
