# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditarperfil():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editarperfil(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(3)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_nameInput__vtFb2:nth-child(1) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_nameInput__vtFb2:nth-child(1) > input").send_keys("Aluno editado")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("alunonovoemail@email.com")
    self.driver.find_element(By.CSS_SELECTOR, ".configuracoes_passwordButton__9S5\\+S:nth-child(1)").click()
    assert self.driver.switch_to.alert.text == "Informações atualizadas com sucesso!"
    self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(1) path").click()
  
