# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeletarrepositrio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deletarrepositrio(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1936, 1048)
    element = self.driver.find_element(By.CSS_SELECTOR, ".menu_topbarBtn__hi2Ji:nth-child(2)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".home_repositoryFlex__64oE-:nth-child(3) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, "svg:nth-child(7)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".updateRepository_buttonDeletarRepository__s-UN5").click()
    assert self.driver.switch_to.alert.text == "Repositório deletado com sucesso!"
  
